services:
  ecommerce_db:
    image: postgres:16
    container_name: ecommerce_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ecommerce_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  ecommerce_web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce_web
    restart: always
    ports:
      - "8081:8080"
    volumes:
      # --- Local Environment (Uncomment this for local development) ---
      # - ./ServiceHost/wwwroot/ProductPictures:/app/wwwroot/ProductPictures

      # --- Production Environment (Uncomment this for VPS/Server) ---
      - /home/MoeinEcommerce/ProductPictures:/app/wwwroot/ProductPictures
    depends_on:
      ecommerce_db:
        condition: service_healthy
    environment:
      - ConnectionStrings__ShopDatabase=Host=ecommerce_db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    networks:
      - ecommerce_network

volumes:
  postgres_data:

networks:
  ecommerce_network:
    driver: bridge
